apiVersion: v1
kind: PersistentVolume
metadata:
  name: duelers-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duelers-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duelers
  labels:
    app: duelers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duelers
  template:
    metadata:
      labels:
        app: duelers
    spec:
      volumes:
        - name: duelers-pv-storage
          persistentVolumeClaim:
            claimName: duelers-pv-claim
      containers:
        - name: duelers
          volumeMounts:
            - mountPath: "/app/Server/resources/accounts"
              name: duelers-pv-storage
          image: duelers/duelers:dedicated_server
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: duelers
spec:
  type: NodePort
  selector:
    app: duelers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
      nodePort: 30888
