apiVersion: apps/v1
kind: Deployment
metadata:
  name: duelers
  labels:
    app: duelers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duelers
  template:
    metadata:
      labels:
        app: duelers
    spec:
      containers:
        - name: duelers
          image: duelers/duelers:dedicated_server
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: duelers
spec:
  type: NodePort
  selector:
    app: duelers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
      nodePort: 30888
