package org.projectcardboard.client.models.account;

import org.projectcardboard.client.models.card.TempDeck;
import shared.models.account.AccountType;
import shared.models.account.BaseTempAccount;

public class TempAccount extends BaseTempAccount<Collection, TempDeck, MatchHistory> {
    public TempAccount( //unused. This is always generated by serialization.
                        String username,
                        String password,
                        AccountType accountType,
                        Collection collection) {
        super(username, password, accountType, collection);
    }
}
